name: Build ZMK firmware
on:
  push:
    paths-ignore:
      - 'assets/**'
      - 'scripts/niceview_lvgl_convert.py'
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - 'assets/**'
      - 'scripts/niceview_lvgl_convert.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
