name: Build ZMK firmware
on:
  push:
    paths-ignore:
      - 'assets/**'
  pull_request:
    paths-ignore:
      - 'assets/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
